backend:
  name: git-gateway
  branch: main

local_backend: true

# Tes médias vivent à la racine de /public
media_folder: "public"   # chemin dans le repo
public_folder: "/"       # URL publique correspondante (ex: /Impact-of-work.png)

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }

          - label: "Site (optional)"
            name: "site"
            widget: "object"
            required: false
            fields:
              - { label: "Name", name: "name", widget: "string", required: false }
              - label: "Nav"
                name: "nav"
                widget: "list"
                required: false
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "URL", name: "href", widget: "string" }

          - label: "Blocks"
            name: "blocks"
            widget: "list"
            types:
              - label: "Header"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "header" }

              - label: "Heading"
                name: "heading"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "heading" }
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Subheading", name: "subheading", widget: "string", required: false }
                  - { label: "Align", name: "align", widget: "select", options: ["left","center","right"], required: false }

              - label: "Stats"
                name: "stats"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "stats" }
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - { label: "Value", name: "value", widget: "string" }
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Description", name: "description", widget: "text", required: false }

              - label: "Values"
                name: "values"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "values" }
                  - label: "Values"
                    name: "values"
                    widget: "list"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Description", name: "description", widget: "text" }

              - label: "Banner"
                name: "banner"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "banner" }
                  # Tu peux garder "string" si tu tapes l'URL à la main (/Impact-of-work.png)
                  # ou mettre "image" si tu veux uploader via l'UI dans /public
                  - { label: "Image URL", name: "src", widget: "string" }
                  - { label: "Item Width (px)", name: "itemWidth", widget: "number" }
                  - { label: "Height (px)", name: "height", widget: "number", required: false }
                  - { label: "Speed (s)", name: "speedSeconds", widget: "number", required: false }
                  - { label: "Gap (px)", name: "gapPx", widget: "number", required: false }
                  - { label: "Count", name: "count", widget: "number", required: false }
