collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }

          - label: "Blocks"
            name: "blocks"
            widget: "list"
            types:
              - label: "Heading"
                name: "heading"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "heading" }
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Subheading", name: "subheading", widget: "string", required: false }
                  - { label: "Align", name: "align", widget: "select", options: ["left", "center", "right"], required: false }

              - label: "Stats"
                name: "stats"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "stats" }
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - { label: "Value", name: "value", widget: "string" }
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Description", name: "description", widget: "text", required: false }

              - label: "Banner"
                name: "banner"
                widget: "object"
                fields:
                  - { label: "Type", name: "type", widget: "hidden", default: "banner" }
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Item Width (px)", name: "itemWidth", widget: "number", value_type: "int" }
                  - { label: "Height (px)", name: "height", widget: "number", value_type: "int", required: false }
                  - { label: "Speed (s)", name: "speedSeconds", widget: "number", value_type: "int", required: false }
                  - { label: "Gap (px)", name: "gapPx", widget: "number", value_type: "int", required: false }
                  - { label: "Count", name: "count", widget: "number", value_type: "int", required: false }
