name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json > /dev/null; then
            npm run lint
          else
            echo "No lint script, skipping"
          fi

      - name: Type-check (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts["type-check"]' package.json > /dev/null; then
            npm run type-check
          else
            echo "No type-check script, skipping"
          fi

      - name: Build
        run: npm run build

      - name: Test (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
            npm test
          else
            echo "No test script, skipping"
          fi
